export const userData = [
  { id: 1, username: "Paul Walker", email: "paulwalker@gmail.com" },
  { id: 2, username: "Angelina Jolie", email: "angelinajolie@gmail.com" },
  { id: 3, username: "Brad Pitt", email: "bradpitt@gmail.com" },
  { id: 4, username: "Leonardo DiCaprio", email: "leonardodicaprio@gmail.com" },
  { id: 5, username: "Jennifer Aniston", email: "jenniferaniston@gmail.com" },
  { id: 6, username: "Johnny Depp", email: "johnnydepp@gmail.com" },
  { id: 7, username: "Natalie Portman", email: "natalieportman@gmail.com" },
  { id: 8, username: "Tom Hanks", email: "tomhanks@gmail.com" },
  {
    id: 9,
    username: "Scarlett Johansson",
    email: "scarlettjohansson@gmail.com",
  },
  { id: 10, username: "George Clooney", email: "georgeclooney@gmail.com" },
  { id: 11, username: "Meryl Streep", email: "merylstreep@gmail.com" },
  { id: 12, username: "Kate Winslet", email: "katewinslet@gmail.com" },
  { id: 13, username: "Robert Downey Jr", email: "robertdowneyjr@gmail.com" },
  { id: 14, username: "Chris Evans", email: "chrisevans@gmail.com" },
  { id: 15, username: "Matt Damon", email: "mattdamon@gmail.com" },
  { id: 16, username: "Cate Blanchett", email: "cateblanchett@gmail.com" },
  { id: 17, username: "Hugh Jackman", email: "hughjackman@gmail.com" },
  { id: 18, username: "Emma Watson", email: "emmawatson@gmail.com" },
  { id: 19, username: "Ryan Reynolds", email: "ryanreynolds@gmail.com" },
  { id: 20, username: "Julia Roberts", email: "juliaroberts@gmail.com" },
  { id: 21, username: "Will Smith", email: "willsmith@gmail.com" },
  { id: 22, username: "Anne Hathaway", email: "annehathaway@gmail.com" },
  {
    id: 23,
    username: "Matthew McConaughey",
    email: "mattewmcconaughey@gmail.com",
  },
  { id: 24, username: "Sandra Bullock", email: "sandrabullock@gmail.com" },
  {
    id: 25,
    username: "Denzel Washington",
    email: "denzelwashington@gmail.com",
  },
  { id: 26, username: "Natalie Dormer", email: "nataliedormer@gmail.com" },
  { id: 27, username: "Chris Pratt", email: "chrispratt@gmail.com" },
  { id: 28, username: "Emily Blunt", email: "emilyblunt@gmail.com" },
  { id: 29, username: "Bradley Cooper", email: "bradleycooper@gmail.com" },
  { id: 30, username: "Chris Hemsworth", email: "chrishemsworth@gmail.com" },
  { id: 31, username: "Idris Elba", email: "idriselba@gmail.com" },
  { id: 32, username: "Jason Statham", email: "jasonstatham@gmail.com" },
  { id: 33, username: "Zendaya", email: "zendaya@gmail.com" },
  { id: 34, username: "Joaquin Phoenix", email: "joaquinphoenix@gmail.com" },
  { id: 35, username: "Gal Gadot", email: "galgadot@gmail.com" },
  { id: 36, username: "Ryan Gosling", email: "ryangosling@gmail.com" },
  { id: 37, username: "Tom Cruise", email: "tomcruise@gmail.com" },
  { id: 38, username: "Harrison Ford", email: "harrisonford@gmail.com" },
  { id: 39, username: "Emma Stone", email: "emmastone@gmail.com" },
  { id: 40, username: "Dwayne Johnson", email: "dwaynejohnson@gmail.com" },
  { id: 41, username: "Charlize Theron", email: "charlizetheron@gmail.com" },
  { id: 42, username: "Tom Hardy", email: "tomhardy@gmail.com" },
  { id: 43, username: "Nicole Kidman", email: "nicolekidman@gmail.com" },
  { id: 44, username: "Keanu Reeves", email: "keanureeves@gmail.com" },
  { id: 45, username: "Margot Robbie", email: "margotrobbie@gmail.com" },
  {
    id: 46,
    username: "Michael Fassbender",
    email: "michaelfassbender@gmail.com",
  },
  { id: 47, username: "Emma Roberts", email: "emmaroberts@gmail.com" },
  {
    id: 48,
    username: "Jennifer Lawrence",
    email: "jenniferlawrence@gmail.com",
  },
  { id: 49, username: "Jake Gyllenhaal", email: "jakegyllenhaal@gmail.com" },
];
